### ISSUE TITLE
Removing `parskip` breaks some stuff

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#12]
I removed the `parskip` package because it's mostly not needed: we do not want paragraph to be separated with empty lines. It was also tampering with other stuff like mathematical environments.

It seems that the only function of `parskip` was to get the formatting of the front matter correct. Hence some lines in the front pages are now incorrectly formatted but this should be easy to fix (by using `\noindent` for instance)

**Comment by Jassob** [comment]
> [..] we do not want paragraph to be separated with empty lines. [..]

We don't? I think that is customary in Swedish writing, but perhaps not in theses?

**Comment by Jassob** [comment]
In any case I think it's good to leave such decision to the end users of the template and not make the choice for them.

**Comment by ayberkt** [comment]
> In any case I think it's good to leave such decision to the end users of the template and not make the choice for them.

Yes, if someone wants to use that style they can simply import `parskip` and that should be it whereas it's quite cumbersome to go the other way.
