### ISSUE TITLE
Acknowledgements page is not included in the TOC

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#13]
The acknowledgements page is not included in the TOC. Should it be?

**Comment by Jassob** [comment]
In the [following example](https://odr.chalmers.se/bitstream/20.500.12380/300609/1/CSE%2019-114%20Lawrence%20Sebastian.pdf) it is not included either.

Then again, if we think that it is best practice to include it I think we should, but the old thesis template did not include it.

**Comment by ayberkt** [comment]
> Then again, if we think that it is best practice to include it I think we should, but the old thesis template did not include it.

It seems to me that this was a mistake by the person who first developed the template. I checked a couple of PhD theses I consider standard in my research subject and they all seem to include both the abstract and the acknowledgements page in the TOC. It is also self-inconsistent that other pages in the front matter are included in the TOC but not abstract and acknowledgements.

**Comment by ayberkt** [comment]
> It seems to me that this was a mistake by the person who first developed the template. I checked a couple of PhD theses I consider standard in my research subject and they all seem to include both the abstract and the acknowledgements page in the TOC. It is also self-inconsistent that other pages in the front matter are included in the TOC but not abstract and acknowledgements.

I looked at a couple of other theses and it seems that I was wrong about this: acknowledgements and abstract should not be included. However, I think I might have been right about the self-inconsistency: it might be that the list of figures and the list of tables should not be included either but I am not entirely sure. For now, let us just leave it as it is.
