### ISSUE TITLE
Fix caching issue with the CI

### ISSUE THREAD

**Issue by Jassob** [ayberkt/chalmers-msc-thesis-template#18]
As laid out in #17 it is tricky to manage the Tectonic cache in the following setup as GitHub's docker actions binds their home environment from outside of Docker, rendering any Docker-prepared cache useless.

Since I don't want to modify the testing script with ugly hacks to fix this issue (my plan is that the testing script should be usable locally as well as in the CI), my plan forward is to define the CI workflow by using whatever the alternative to Docker is called. 
A benefit of this is that we actually could cache quite much of the setup in that case, for instance the Tectonic binary and deps _AND_ the TeX cache.

**Comment by ayberkt** [comment]
I don't have much experience with GitHub actions so I can't help with this. Why don't we simply prime tectonic in the Docker image though? It stores LaTeX libraries in a global location, right?

**Comment by Jassob** [comment]
> It stores LaTeX libraries in a global location, right?

No, it stores the files inside $HOME/.cache/Tectonic, but then GitHub overrides the HOME variable so that it points to a directory they've mounted themselves (effectively shadowing whatever directory was present there before).

> I don't have much experience with GitHub actions so I can't help with this. Why don't we simply prime tectonic in the Docker image though?

That's what I've tried to do, but the cache is ignored because it is a user-local cache.

I might investigate to override $HOME (or whatever XDG-variable controls the cache-directory), but I would prefer not to contaminate the `run-tests.sh` script.

**Comment by ayberkt** [comment]
Ah, I see. It was issues like this that made me switch to GitLab for major projects.

**Comment by Jassob** [comment]
Yeah, I understand that the GitLab CI story is quite good, at least compared to GitHub.
