### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by Jassob** [ayberkt/chalmers-msc-thesis-template#19]
I think we should activate branch protection for the master branch. I noticed that I've accidentally pushed two commits (https://github.com/ayberkt/chalmers-msc-thesis-template/commit/1ed43c84b50fdb4fa3400ec34a40fd6bfdb7ec5b, https://github.com/ayberkt/chalmers-msc-thesis-template/commit/f3842876b482e49965aaa101ade9630cc279e049, feel free to rebase the history and remove, or revert) to master, believing that I pushed them to my own fork..

The branch protection should disable push access to master and force us to use PR's for adding commits to the master branch. This might seem a bit too strict for a project such as this, but keep in mind that you can always merge a PR even if no-one has approved it. 

See the [documentation](https://help.github.com/en/github/administering-a-repository/configuring-protected-branches) for more information and how-to's.

What do you think (and sorry for force-pushing to your repo!)?

**Comment by ayberkt** [comment]
I thought I had already enabled branch protection. Let me check.

**Comment by ayberkt** [comment]
Yes, branch protection is enabled for `master` and "the allow force pushing" box is not checked so I don't know how you have been able to to force push. Maybe this was before that?

**Comment by Jassob** [comment]
Yes, this was probably the same day you gave me push access to this repo. Alright, very well then.
I'll close the issue in that case then.
