### ISSUE TITLE
Omit all mentions to subtitle if none is provided

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#2]

**Comment by Jassob** [comment]
I can try to fix this, since I have been looking into subtitles lately.

**Comment by Jassob** [comment]
The template currently fails if a subtitle is not provided, instead of silently defaulting to "Subtitle".

**Comment by ayberkt** [comment]
@Jassob I suppose a simple if-def would work for this. I found an example here: https://tex.stackexchange.com/questions/33576/conditional-typesetting-build.

**Comment by Jassob** [comment]
Great, thanks!
