### ISSUE TITLE
Inform administration people of the existence of this template

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#24]
As this template seems to be coming together, I think we can let Birgit Grohe know so that she can add a link in the Canvas page.

**Comment by Jassob** [comment]
That is a very good idea, but I think we need to add a license to it first.

**Comment by Jassob** [comment]
I really don't care about which license we use, I just don't want it to be a license which could cause other people trouble.

**Comment by ayberkt** [comment]
#29 adds a licence.

**Comment by ayberkt** [comment]
[Birgit Grohe](https://www.chalmers.se/sv/personal/Sidor/grohe.aspx) has been informed.
