### ISSUE TITLE
Acknowledge everyone who worked on the original template

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#25]

**Comment by Jassob** [comment]
~I think this is a very good point. We could have a "Thanks"-section in the README.md or something and then remove the comment headers in the files.~

If I had looked in the PR's prior to checking this issue I would have seen that you've already done the same thing. Good work, I think the #26 is even better than a Thanks-section.

**Comment by ayberkt** [comment]
I referenced the issue actually but I guess it has to referenced in a comment inside the PR.

**Comment by Jassob** [comment]
Hmm, yeah you probably need to put the "resolves ..." line in the PR body or commit message..
