### ISSUE TITLE
Chalmers and GU logos on page 3 must be boxed

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#5]

**Comment by ayberkt** [comment]
I thought this was the case in the original template but after checking again I noticed that it is not. I'm pretty sure I've seen this title page with the Chalmers/GU logos boxed at some point but I don't know where. Maybe it was a modification made by the author of a master's thesis I looked at at some point.

@Jassob I'm closing this then?

**Comment by Jassob** [comment]
I'm not really sure what you mean, but unless you can find an example of boxed logos then I am all for closing this issue.

**Comment by ayberkt** [comment]
> unless you can find an example of boxed logos

Here is an example: https://limperg.de/paper/msc-thesis/paper.pdf.

However, I think we should stick with the template's choice on this one.

**Comment by Jassob** [comment]
> However, I think we should stick with the template's choice on this one.

Agree!
