### ISSUE TITLE
Set up continuous testing

### ISSUE THREAD

**Issue by ayberkt** [ayberkt/chalmers-msc-thesis-template#9]
@Jassob I created a Docker image equipped with the minimum requirements for compiling this template (including the fonts): https://hub.docker.com/r/ayberkt/latex.

Can you use it to set up CI testing using GitHub actions? I have no idea how to use it since I use GitLab for this purpose.

**Comment by Jassob** [comment]
Yes, absolutely! I've also been thinking about how to go about CI here. 
Maybe we can do some golden testing by having a sample document compiled with the original template and make sure that the PDF produced from the same document, but with our template, matches the original PDF. 

This would let us have a baseline for when we at least think that we only change ergonomics and not anything observable.

**Comment by ayberkt** [comment]
> Maybe we can do some golden testing by having a sample document compiled with the original template and make sure that the PDF produced from the same document, but with our template, matches the original PDF.

Sounds good. I suppose byte-wise different PDF files might be visually identical. To compare the visual output, we may use [ImageMagick's `compare`](https://imagemagick.org/script/compare.php).

**Comment by Jassob** [comment]
> Sounds good. I suppose byte-wise different PDF files might be visually identical. To compare the visual output, we may use ImageMagick's compare<https://imagemagick.org/script/compare.php>.

That's probably true, but I think that as long as we don't have any dynamic content (i.e. date is set to something other than \today)
and the different macros we use all expand to the exactly same strings, then the PDF's should be identical, even on byte-level.
This is of course an untested hypothesis, but I've tried it with trivial changes and in those cases the PDF is byte-wise identical,
so I think it is worth a try to keep it simple.

**Comment by ayberkt** [comment]
@Jassob okay, let's start with that then.
